version: "3.7"

services:
  market:
    container_name: market
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  market: 